version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pgsql
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TestsDB
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
